### ISSUE TITLE
VarIntField error

### ISSUE THREAD

**Issue by brumik** [jbcayrou/scapy-bitcoin#3]
Hello, I am not expert in python especially not scapy, and the `VarIntField` throws an error:

```
ile "/home/brum/Documents/Bitcoin/sample-generator/bitcoin.py", line 244, in addfield
    if val < 0xfd:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```
It is occurring when I let the `count` field to be calculated by the length of the array.
Example:
```python
pkt = BitcoinHdr() / BitcoinNotfound(
        inventory = [
            InventoryPktField(hash = "NotfoundRandomHash"),
            InventoryPktField(hash = "NotfoundHashRandom"),
        ]
    )
```
Also I get similar error when I try to use `VarIntField` to specify explicitly the count of a field. (Exception if I use a number smaller than 0xfd because then it is just a number and I don't need to encode it)

Another possible indent error is on line 209:
```python
    def i2m(self, pkt, x):
        if x is None:
            if self.length_of is not None:
                fld,fval = pkt.getfield_and_val(self.length_of)
                f = fld.i2len(pkt, fval)
            x = f # <----------------------------- Here
        return x
```
Is there a chance you can look into it in the following days?
Thank you.

**Comment by evens64** [comment]
This error arises from different behavior of struct.pack(fmt, v1, v2, ...) function in Python2 vs Python3. In Python 2 the original code works great - no need to fix this. However I agree with the indentation error. With current indentation there is a possibility of assigning not defined variable.
